#!/usr/bin/env python3
"""Generate QEMU compatibility entries for exact shadPS4 success stubs.

This intentionally accepts only functions whose body, after removing logging
and comments, is a single successful return.  Functions which validate input,
write output memory, or maintain state must be ported as real HLE handlers.
"""

import argparse
import collections
import pathlib
import re


HLE_MAP_RE = re.compile(
    r'HLE_MAP\("([^"]+)",\s*(SHADPS4_HLE_[A-Z0-9_]+|[0-9]+)\)')
STATIC_EXPORT_RE = re.compile(
    r'SHADPS4_HLE_EXPORT\(\s*"([^"]+)"\s*,\s*"[^"]+"\s*,\s*'
    r'(SHADPS4_HLE_[A-Z0-9_]+|[0-9]+)\s*\)')
STATIC_ENTRY_RE = re.compile(
    r'\{\s*"([^"]+)"\s*,\s*"[^"]+"\s*,\s*"[^"]+"\s*,\s*'
    r'(SHADPS4_HLE_[A-Z0-9_]+|[0-9]+)\s*[,}]')
LIB_FUNCTION_RE = re.compile(r"LIB_FUNCTION\((.*?)\);", re.S)
FUNCTION_RE_TEMPLATE = r"\b%s\s*\([^;{}]*\)\s*\{"
SUCCESS_BODY_RE = re.compile(
    r"return\s+(?:ORBIS_OK|ORBIS_SUCCESS|0|false|"
    r"Libraries::CommonDialog::Status::NONE)\s*;"
)


def function_body(source, qualified_name):
    name = qualified_name.rsplit("::", 1)[-1]
    pattern = re.compile(FUNCTION_RE_TEMPLATE % re.escape(name), re.S)
    for match in pattern.finditer(source):
        opening = source.find("{", match.start())
        depth = 0
        quote = None
        escaped = False
        line_comment = False
        block_comment = False
        index = opening
        while index < len(source):
            char = source[index]
            following = source[index + 1] if index + 1 < len(source) else ""
            if line_comment:
                line_comment = char != "\n"
            elif block_comment:
                if char == "*" and following == "/":
                    block_comment = False
                    index += 1
            elif quote:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == quote:
                    quote = None
            elif char == "/" and following == "/":
                line_comment = True
                index += 1
            elif char == "/" and following == "*":
                block_comment = True
                index += 1
            elif char in {'"', "'"}:
                quote = char
            elif char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return source[opening + 1:index]
            index += 1
    return None


def is_exact_success_stub(body):
    if body is None:
        return False
    body = re.sub(r"/\*.*?\*/|//[^\n]*", "", body, flags=re.S)
    body = re.sub(r"\bLOG_[A-Z]+\s*\(.*?\)\s*;", "", body, flags=re.S)
    body = re.sub(r"\bHLE_TRACE\s*;", "", body)
    body = re.sub(r"\(void\)\s*[A-Za-z_][A-Za-z0-9_]*\s*;", "", body)
    normalized = " ".join(body.split())
    return not normalized or bool(SUCCESS_BODY_RE.fullmatch(normalized))


def collect(qemu_root, shadps4_root):
    qemu_source = (qemu_root / "hw/i386/shadps4.c").read_text("utf-8")
    mapped = {nid for nid, _dispatch in HLE_MAP_RE.findall(qemu_source)}
    mapped.update(nid for nid, _dispatch in STATIC_EXPORT_RE.findall(qemu_source))
    mapped.update(nid for nid, _dispatch in STATIC_ENTRY_RE.findall(qemu_source))
    gnm_start = qemu_source.find("static uint32_t shadps4_gnm_compat_dispatch")
    gnm_end = qemu_source.find("typedef struct ShadPS4HLECompatMap", gnm_start)
    if gnm_start >= 0 and gnm_end > gnm_start:
        mapped.update(re.findall(
            r'(?:\\||")([A-Za-z0-9+_-]{11})(?=\\||")',
            qemu_source[gnm_start:gnm_end]))
    grouped = collections.defaultdict(set)
    reviewed = collections.defaultdict(set)
    unresolved = []
    libraries = shadps4_root / "src/core/libraries"

    for path in libraries.rglob("*.cpp"):
        source = path.read_text("utf-8", errors="ignore")
        for registration in LIB_FUNCTION_RE.finditer(source):
            arguments = registration.group(1)
            strings = re.findall(r'"([^"]*)"', arguments)
            function = re.search(
                r",\s*([A-Za-z_][A-Za-z0-9_:~]*)\s*$", arguments)
            if len(strings) < 3 or not function or strings[0] in mapped:
                continue
            body = function_body(source, function.group(1))
            if is_exact_success_stub(body):
                grouped[strings[2]].add(strings[0])
            else:
                reviewed[strings[2]].add(strings[0])
                if body is None:
                    unresolved.append((path, function.group(1), strings[0]))
    return grouped, reviewed, unresolved


def render(grouped, label="Exact success stubs"):
    count = sum(len(nids) for nids in grouped.values())
    lines = [
        "/* Generated by scripts/shadps4-generate-trivial-providers.py.",
        " * Source: shadPS4 src/core/libraries providers.",
        f" * {label}: {count} NIDs in {len(grouped)} modules.",
        " * Generated entries must not be edited by hand.",
        " */",
    ]
    if label == "Non-trivial reviewed providers":
        lines.append(f"#define SHADPS4_HLE_REVIEWED_PROVIDER_COUNT {count}")
    for module in sorted(grouped):
        nids = "|" + "|".join(sorted(grouped[module])) + "|"
        lines.append(f'{{ "{module}", "{nids}" }},')
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--qemu-root", type=pathlib.Path,
                        default=pathlib.Path(__file__).resolve().parents[1])
    parser.add_argument("--shadps4-root", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--review-output", type=pathlib.Path)
    args = parser.parse_args()
    grouped, reviewed, unresolved = collect(args.qemu_root, args.shadps4_root)
    # Unresolved definitions are conservatively excluded, never treated as stubs.
    args.output.write_text(render(grouped), "utf-8")
    if args.review_output:
        args.review_output.write_text(
            render(reviewed, "Non-trivial reviewed providers"), "utf-8")


if __name__ == "__main__":
    main()
